
	<div class="account-page">
		<div class="container">
			<?php
			if (isset($_SESSION['flash_message'])) {
    		echo "<div id='errorMessage' style='background-color: #f8d7da; color: #721c24; padding: 10px; border: 1px solid #f5c6cb; border-radius: 5px; margin-top: 10px;'>
            <strong>Warning!</strong> " . htmlspecialchars($_SESSION['flash_message']) . "
          </div>";
		  unset($_SESSION['flash_message']);
}
			?>

			<div class="row">
				<div class="col-2">
					<img src="Images/livres.png" width="100%">
				</div>
				<div class="col-2">
					<div class="form-container">
						<div class="form-btn">
							<span onclick="login()">Login</span>
							<span onclick="register()">Register</span>
							<hr id="Indicator">
						</div>
						
						<form action="login.php" method="POST" id="LoginForm">
							<input type="email" placeholder="Email" name="email">
							<input type="password" placeholder="Password" name="password">
							<button type="submit" class="btn" name="loginSubmit">Login</button>
							<a href="">Forgot Password</a>
						</form>
						
						<form action="signin.php" method="GET" id="RegForm">
							<input type="text" placeholder="Username" name="username" >
							<input type="email" placeholder="Email" name="email">
							<input type="password" placeholder="Password" name="password">
							<button type="submit" class="btn" name="regSubmit">Register</button>
						</form>
					</div>
				</div>

			</div>
				


		</div>
		
	</div>

    
	<div class="footer">
		<div class="container">
			<div class="row">
				<div class="footer-col-2">
					<img src="Images/BookLand - Logo (White).png">
					<p>Our Purpose Is To Sustainably Make the Pleasure and
						<br>Benifits of Books to the Many.</p>
				</div>
				
		
			</div>
			<hr>
			<p class="copyright">Copyright 2021 - Book Landd</p>
		</div>
	</div>
	<script>
		var LoginForm = document.getElementById("LoginForm");
		var RegForm = document.getElementById("RegForm");
		var Indicator = document.getElementById("Indicator");
		
			function register(){
				RegForm.style.transform = "translateX(0px)";
				LoginForm.style.transform = "translateX(0px)";
				Indicator.style.transform = "translateX(100px)";
			}
		
			function login(){
				RegForm.style.transform = "translateX(300px)";
				LoginForm.style.transform = "translateX(300px)";
				Indicator.style.transform = "translateX(0px)";
			}
	</script>


</body>
</html>
	